### ISSUE TITLE
Work on Config 2.0

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-parent#91]

**Comment by radcortez** [comment]
High Level Overview for MP 2.0:

- [ ] Expose Conversion in Config API - https://github.com/eclipse/microprofile-config/issues/492
- [ ] Configuration Profiles - https://github.com/eclipse/microprofile-config/issues/418
- [ ] Variable Replacement - https://github.com/eclipse/microprofile-config/issues/118
- [ ] Config Value Metadata - https://github.com/eclipse/microprofile-config/issues/43
